version: "3.8"

services:

    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - "1434:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12#!#
        volumes: 
            - sqldata:/var/opt/mssql 
        networks: 
            - restaurantmanagement_network
            
    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports: 
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmquser
            - RABBITMQ_DEFAULT_PASS=rabbitmqPassword12!
        networks: 
            - restaurantmanagement_network
    
    kitchen:
        container_name: kitchen_api
        image: zapryanbekirski/restaurantmanagement_kitchenapi
        build:
            context: ./RestaurantManagement
            dockerfile: ./Kitchen.API/Dockerfile
        ports: 
            - "56902:80"
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RestaurantManagementSystem;User Id=sa; Password=yourStrongPassword12#!#;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        networks: 
            - restaurantmanagement_network
        depends_on:
            - data
            - messages
            
    identity:
        container_name: identity_api
        image: zapryanbekirski/restaurantmanagement_identityapi
        build:
            context: ./RestaurantManagement
            dockerfile: ./Identity.API/Dockerfile
        ports: 
            - "56747:80"
        environment:
            - ApplicationSettings__Secret=S0M3 M4G1C UN1C0RNS G3N3R4T3D TH1S S3CR3T
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RestaurantManagementSystem;User Id=sa; Password=yourStrongPassword12#!#;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        networks: 
            - restaurantmanagement_network
        depends_on:
            - data
            - messages
            
    serving:
        container_name: serving_api
        image: zapryanbekirski/restaurantmanagement_servingapi
        build:
            context: ./RestaurantManagement
            dockerfile: ./Serving.API/Dockerfile
        ports: 
            - "54695:80"
        environment:
            - ApplicationSettings__Secret=S0M3 M4G1C UN1C0RNS G3N3R4T3D TH1S S3CR3T
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RestaurantManagementSystem;User Id=sa; Password=yourStrongPassword12#!#;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        networks: 
            - restaurantmanagement_network
        depends_on:
            - data
            - messages
            
    hosting:
        container_name: hosting_api
        image: zapryanbekirski/restaurantmanagement_hostingapi
        build:
            context: ./RestaurantManagement
            dockerfile: ./Hosting.API/Dockerfile
        ports: 
            - "52008:80"
        environment:
            - ApplicationSettings__Secret=S0M3 M4G1C UN1C0RNS G3N3R4T3D TH1S S3CR3T
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RestaurantManagementSystem;User Id=sa; Password=yourStrongPassword12#!#;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        networks: 
            - restaurantmanagement_network
        depends_on:
            - data
            - messages

networks:
    restaurantmanagement_network:

volumes:
    sqldata:
