apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  clusterIP: None
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    database: common

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
spec:
  serviceName: sqlserver
  selector:
    matchLabels: 
      database: common
  template:
    metadata:
      labels:
        database: common
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 10001
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: database-sa-password
        volumeMounts:
        - name: sqldata
          mountPath: /var/opt/mssql
      volumes:
      - name: sqldata
        persistentVolumeClaim:
          claimName: database-data
    