apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  event-bus-host: event-bus
  event-bus-user: rabbitmquser

---

apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
  database-sa-password: eW91clN0cm9uZ1Bhc3N3b3JkMTIjISM=
  database-connection-string: U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1SZXN0YXVyYW50TWFuYWdlbWVudFN5c3RlbTtVc2VyIElkPXNhOyBQYXNzd29yZD15b3VyU3Ryb25nUGFzc3dvcmQxMiMhIztNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZQ==
  security-token-secret: UzBNMyBNNEcxQyBVTjFDMFJOUyBHM04zUjRUM0QgVEgxUyBTM0NSM1Q=
  event-bus-password: cmFiYml0bXFQYXNzd29yZDEyIQ==