apiVersion: v1
kind: Service
metadata:
  name: hosting-api
spec:
  type: LoadBalancer
  ports:
  - port: 52008
    targetPort: 80
  selector:
    web-api: hosting-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hosting-api
spec:
  selector:
    matchLabels:
      web-api: hosting-api
  template:
    metadata:
      labels:
        web-api: hosting-api
    spec:
      containers:
      - name: hosting-api
        image: zapryanbekirski/restaurantmanagement_hostingapi:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=RestaurantManagementSystem;User Id=sa; Password=yourStrongPassword12#!#;MultipleActiveResultSets=true"
        - name: MessageQueueSettings__Host
          value: "event-bus"
        - name: MessageQueueSettings__UserName
          value: "rabbitmquser"
        - name: MessageQueueSettings__Password
          value: "rabbitmqPassword12!"
        - name: ApplicationSettings__Secret
          value: "S0M3 M4G1C UN1C0RNS G3N3R4T3D TH1S S3CR3T"
     
