apiVersion: v1
kind: Service
metadata:
  name: kitchen-api
spec:
  type: LoadBalancer
  ports:
  - port: 56902
    targetPort: 80
  selector:
    web-api: kitchen-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-api
spec:
  selector:
    matchLabels:
      web-api: kitchen-api
  template:
    metadata:
      labels:
        web-api: kitchen-api
    spec:
      containers:
      - name: kitchen-api
        image: zapryanbekirski/restaurantmanagement_kitchenapi:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=RestaurantManagementSystem;User Id=sa; Password=yourStrongPassword12#!#;MultipleActiveResultSets=true"
        - name: MessageQueueSettings__Host
          value: "event-bus"
        - name: MessageQueueSettings__UserName
          value: "rabbitmquser"
        - name: MessageQueueSettings__Password
          value: "rabbitmqPassword12!"
     
