apiVersion: v1
kind: Service
metadata:
  name: serving-api
spec:
  type: LoadBalancer
  ports:
  - port: 54695
    targetPort: 80
  selector:
    web-api: serving-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-api
spec:
  replicas: 3
  selector:
    matchLabels:
      web-api: serving-api
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        web-api: serving-api
    spec:
      containers:
      - name: serving-api
        image: zapryanbekirski/restaurantmanagement_servingapi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        env:
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: database-connection-string
        - name: MessageQueueSettings__Host
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-host
        - name: MessageQueueSettings__UserName
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-user
        - name: MessageQueueSettings__Password
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: event-bus-password
        - name: ApplicationSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
     
